ALTER TABLE db_version CHANGE COLUMN required_z1824_xxxxx_01_mangos_spell_affect_event required_z1838_xxxxx_01_mangos_drop_tbc bit;

DROP TABLE IF EXISTS skill_discovery_template;
DROP TABLE IF EXISTS skill_extra_item_template;
